version:  "3.9"
services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:1234@db:5432/employee_db
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
        POSTGRES_USER : myuser
        POSTGRES_PASSWORD : 1234
        POSTGRES_DB : employee_db
    ports:  
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d employee_db"]
      interval: 5s
      retries: 5
      timeout: 5s